### ISSUE TITLE
Using explorer UI in local cloud

### ISSUE THREAD

**Issue by OnurErtunc** [eclipse/packages#426] opened 2022-10-10 15:26 UTC
Can we use the Explorer UI of the ditto in local cloud2edge? If so, how?

**Comment by thjaeckle** [comment] 2022-10-11 13:11
The Ditto UI is not yet included in Ditto's or cloud2edge's chart - we have issue #418 to track that (but did not yet find time to do so).
If you find the time, we would appreciate a PR 👍 

In the meantime you can just run it, e.g. via Docker (e.g. starting it to be available on port 8088 on the host machine):
```bash
docker run -p 8088:8080 eclipse/ditto-ui
```

For deployment in Kubernetes this would of course have to look different.

**Comment by thjaeckle** [comment] 2022-11-06 10:32
Closing as duplicate of #418

**Closed** 2022-11-06 10:32 UTC
